name       : asciidoc
version    : 9.0.0
release    : 9
source     :
    - https://github.com/asciidoc/asciidoc-py3/archive/9.0.0rc1.tar.gz : 8d5a22039943e43374eedaa1ea3e17a79bf29dd671918c090f535b1b3c6c0997
license    : GPL-2.0-or-later
homepage   : http://asciidoc.org/
component  : office
summary    : AsciiDoc is a text document format for writing notes, documentation, and more.
description: |
    AsciiDoc is a text document format for writing notes, documentation, and more.
builddeps  :
    - pkgconfig(libxslt)
    - docbook-xml
rundeps    :
    - docbook-xml
    - libxslt
    - fop
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
