name       : asciidoc
version    : 9.0.0
release    : 10
source     :
    - https://github.com/asciidoc/asciidoc-py3/archive/9.0.0.tar.gz : 04f219e24476ce169508917766e93279d13b3de69ae9ce40fdfd908162e441c4
license    : GPL-2.0-or-later
homepage   : http://asciidoc.org/
component  : office
summary    : AsciiDoc is a text document format for writing notes, documentation, and more.
description: |
    AsciiDoc is a text document format for writing notes, documentation, and more.
builddeps  :
    - pkgconfig(libxslt)
    - docbook-xml
rundeps    :
    - docbook-xml
    - libxslt
    - fop
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
