name       : asciidoc
version    : 8.6.10
release    : 8
source     :
    - https://github.com/asciidoc/asciidoc/archive/8.6.10.tar.gz : 9e52f8578d891beaef25730a92a6e723596ddbd07bfe0d2a56486fcf63a0b983
license    : GPL-2.0-or-later
component  : office
summary    : AsciiDoc is a text document format for writing notes, documentation, and more.
description: |
    AsciiDoc is a text document format for writing notes, documentation, and more.
builddeps  :
    - pkgconfig(libxslt)
    - docbook-xml
rundeps    :
    - docbook-xml
    - libxslt
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
