name       : asciidoc
version    : 8.6.9
release    : 5
source     :
    - http://freefr.dl.sourceforge.net/project/asciidoc/asciidoc/8.6.9/asciidoc-8.6.9.tar.gz : 78db9d0567c8ab6570a6eff7ffdf84eadd91f2dfc0a92a2d0105d323cab4e1f0
license    : GPL-2.0-or-later
component  : office
summary    : AsciiDoc is a text document format for writing notes, documentation, and more.
description: |
    AsciiDoc is a text document format for writing notes, documentation, and more.
builddeps  :
    - pkgconfig(libxslt)
    - docbook-xml
rundeps:
    - docbook-xml
    - libxslt
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
